name: Testing workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Run unittests"
        run: python -m unittest test_operations_unittests.py