name: Testing workflow

on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Install style checker"
        run: pip install black
      - name: "Run style check"
        run: black --check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Install coverage"
        run: pip install -U coverage
      - name: "Run pytest with coverage"
        run: coverage run -m pytest
      - name: "Upload .coverage as artifact"
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: .coverage
          retention-days: 1
